import type { Metadata } from "next";
import "./globals.css";
import VisualHero from "@/components/VisualHero";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { AnimationProvider } from "@/contexts/AnimationContext";
import ThemeToggle from "@/components/ThemeToggle";
import AnimationToggle from "@/components/AnimationToggle";
import SettingsToggle from "@/components/SettingsToggle";
import CircularTextWrapper from "@/components/CircularTextWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider>
          <AnimationProvider>
            <VisualHero />
            <ThemeToggle />
            <AnimationToggle />
            <SettingsToggle />
            <CircularTextWrapper />
            <div style={{ position: 'relative', zIndex: 20 }}>
              {children}
            </div>
          </AnimationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
