import type { Metadata } from "next";
import "./globals.css";
import CircularText from "@/components/CircularText";
import VisualHero from "@/components/VisualHero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* Site-wide visual + hero (client-only) */}
        <VisualHero />

        {/* Circular rotating logo top-right on every page */}
        <div style={{ position: 'fixed', right: 12, top: 12, pointerEvents: 'auto', zIndex: 40, transform: 'scale(0.7)', transformOrigin: 'top right' }}>
          <CircularText text="ASK*EXPLORE*MASTER*" spinDuration={60} className="string" />
        </div>

        {/* Main content wrapper — positioned above the background visual */}
        <div style={{ position: 'relative', zIndex: 20 }}>
          {children}
        </div>
      </body>
    </html>
  );
}
